import Layout from "@/components/layout";
import Product from "@/components/product";
import { Carousel, Col, Image, Row, Typography } from "antd";
import Head from "next/head";
import type { productProps } from "@/components/product";
import styles from "@/styles/home.module.scss";
import Blog from "@/components/blog";
import { LeftCircleOutlined, RightCircleOutlined } from "@ant-design/icons";
import Link from "next/link";

const productItem: productProps = {
  id: "air_jordan_1_mid_light",
  name: "AIR JORDAN 1 MID LIGHT CARDINAL CURRY (GS) [554725-201]",
  theme: "/91-7329.jpg",
  images: ["/91-7329.jpg", "/91-7329.jpg", "/91-7329.jpg"],
  price: 4200000,
  promotion: 30,
  category: "AIR JORDAN 6",
  brand: "AIR JORDAN",
  productSizes: ["40.0", "40.5", "41.0", "42.0", "43.0"],
  status: "available",
  description: "",
};

export default function Home() {
  const NextButton = ({ currentSlide, slideCount, ...props }: any) => {
    return <RightCircleOutlined {...props} />;
  };

  const PrevButton = ({ currentSlide, slideCount, ...props }: any) => {
    return <LeftCircleOutlined {...props} />;
  };

  return (
    <>
      <Head>
        <title>Sneaker Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/main-logo.jpg" />
      </Head>
      <main>
        <Layout>
          <Row
            gutter={16}
            id="categoriesPanel"
            className={styles.contentSection}
          >
            <Col span={6}>
              <Link
                href="/"
                title="Air Jordan 1"
                className={"relative block " + styles.categoryTab}
              >
                <div className="overflow-hidden">
                  <Image
                    className={styles.categoryTab_theme}
                    src="/tm1.jpg"
                    alt="Air Force 1"
                    preview={false}
                  />
                </div>
                <Typography.Title
                  level={4}
                  className={
                    "bg-white bottom-0 absolute text-center left-3 right-3 text-sm " +
                    styles.categoryTab_title
                  }
                >
                  Air Force 1
                </Typography.Title>
              </Link>
            </Col>
            <Col span={6}>
              <Link
                href="/"
                title="Air Jordan 1"
                className={"relative block " + styles.categoryTab}
              >
                <div className="overflow-hidden">
                  <Image
                    className={styles.categoryTab_theme}
                    src="/tm2.jpg"
                    alt="Air Force 1"
                    preview={false}
                  />
                </div>
                <Typography.Title
                  level={4}
                  className={
                    "bg-white bottom-0 absolute text-center left-3 right-3 text-sm " +
                    styles.categoryTab_title
                  }
                >
                  Air Jordan 1
                </Typography.Title>
              </Link>
            </Col>
            <Col span={6}>
              <Link
                href="/"
                title="Air Jordan 1"
                className={"relative block " + styles.categoryTab}
              >
                <div className="overflow-hidden">
                  <Image
                    className={styles.categoryTab_theme}
                    src="/tm4.jpg"
                    alt="Air Force 1"
                    preview={false}
                  />
                </div>
                <Typography.Title
                  level={4}
                  className={
                    "bg-white bottom-0 absolute text-center left-3 right-3 text-sm " +
                    styles.categoryTab_title
                  }
                >
                  Ultra Boost
                </Typography.Title>
              </Link>
            </Col>
            <Col span={6}>
              <Link
                href="/"
                title="Air Jordan 1"
                className={"relative block " + styles.categoryTab}
              >
                <div className="overflow-hidden">
                  <Image
                    className={styles.categoryTab_theme}
                    src="/tm3.jpg"
                    alt="Air Force 1"
                    preview={false}
                  />
                </div>
                <Typography.Title
                  level={4}
                  className={
                    "bg-white bottom-0 absolute text-center left-3 right-3 text-sm " +
                    styles.categoryTab_title
                  }
                >
                  Air Max 1
                </Typography.Title>
              </Link>
            </Col>
          </Row>
          <Row gutter={16} id="newReleases" className={styles.contentSection}>
            <Col span={24}>
              <Typography.Title
                level={1}
                className="text-center tracking-wider"
              >
                NEW RELEASES
              </Typography.Title>
            </Col>
            <Col span={24} className="relative">
              <Carousel
                autoplay
                dots={false}
                slidesToShow={4}
                arrows
                prevArrow={<PrevButton />}
                nextArrow={<NextButton />}
              >
                <Product {...productItem} />
                <Product {...productItem} />
                <Product {...productItem} />
                <Product {...productItem} />
                <Product {...productItem} />
                <Product {...productItem} />
                <Product {...productItem} />
                <Product {...productItem} />
              </Carousel>
            </Col>
          </Row>
          <Row gutter={16} id="topSellers" className={styles.contentSection}>
            <Col span={24}>
              <Typography.Title
                level={1}
                className="text-center tracking-wider"
              >
                TOP SELLERS
              </Typography.Title>
            </Col>
            <Col span={24} className="relative">
              <Carousel
                dots={false}
                autoplay
                slidesToShow={4}
                arrows
                prevArrow={<PrevButton />}
                nextArrow={<NextButton />}
              >
                <Product {...productItem} />
                <Product {...productItem} />
                <Product {...productItem} />
                <Product {...productItem} />
                <Product {...productItem} />
                <Product {...productItem} />
                <Product {...productItem} />
                <Product {...productItem} />
              </Carousel>
            </Col>
          </Row>
          <Row gutter={16} id="blogs" className={styles.contentSection}>
            <Col span={24}>
              <Typography.Title
                level={1}
                className="text-center tracking-wider"
              >
                BLOGS
              </Typography.Title>
            </Col>
            <Col span={8}>
              <Blog />
            </Col>
            <Col span={8}>
              <Blog />
            </Col>
            <Col span={8}>
              <Blog />
            </Col>
            <Col span={24} className="text-center mt-8">
              <Link href="/1">View more</Link>
            </Col>
          </Row>
          <Row gutter={16} id="about" className={styles.contentSection}>
            <Col span={12}>
              <div className="h-[800px] w-full border border-gray-400"></div>
            </Col>
            <Col span={12} className="flex justify-center">
              <div className="max-w-[80%]">
                <Typography.Paragraph className="text-3xl font-semibold text-gray-500">
                  Sneaker Store
                </Typography.Paragraph>
                <blockquote className="border-l-[5px] block border-gray-200 px-5 py-2">
                  <Typography.Paragraph className="text-lg font-medium text-gray-600">
                    Trong xu thế nền văn hóa sát mặt đất và ngành công nghiệp
                    thời trang đường phố đang rất phát triển tại Việt Nam, hàng
                    trăm cửa hàng nổi lên, không hề có sự chọn lọc nhất định,
                    kèm theo đó là một số vấn đề liên tục phát sinh khiến ta đắn
                    đó quyết định mua item yêu thích của mình.
                  </Typography.Paragraph>
                </blockquote>
                <Typography.Text className="text-md py-3 block text-base font-medium">
                  Online Sneaker Store là một trong những cửa hàng về sneakers
                  chính hãng đầu tiên tại Việt Nam nói chung và Sài Gòn nói
                  riêng. Qua nhiều năm phát triển và tạo dựng uy tín, bên cạnh
                  mặt hàng sneaker thì Online Sneaker Store ngày này còn phân
                  phối nhiều mặt hàng chính hãng khác như quần áo, túi xách, phụ
                  kiện.
                </Typography.Text>
              </div>
            </Col>
          </Row>
        </Layout>
      </main>
    </>
  );
}
