import Layout from "@/components/layout";
import Product from "@/components/product";
import { ShopSidebar } from "@/components/sidebar";
import dbConnector from "@/database";
import ProductModel from "@/database/models/product";
import { ProductInterface } from "@/interfaces";
import { Col, Pagination, Row } from "antd";
import { GetStaticProps } from "next";
import Head from "next/head";
import { Suspense } from "react";
import Loading from "./loading";

type sidebarOptionProps = {
  key: string;
  label: string;
  value: string;
};

export type sidebarItemProps = {
  key: string;
  label: string;
  type: "checkbox" | "radio";
  options: Array<sidebarOptionProps>;
};

const SidebarItems = {
  brands: {
    key: "brands",
    label: "Brands",
    type: "checkbox",
    options: [
      {
        key: "nike",
        label: "Nike",
        value: "nike",
      },
      {
        key: "adidas",
        label: "Adidas",
        value: "adidas",
      },
      {
        key: "puma",
        label: "Puma",
        value: "puma",
      },
      {
        key: "reebok",
        label: "Reebok",
        value: "Reebok",
      },
      {
        key: "jordan",
        label: "Jordan",
        value: "jordan",
      },
    ],
  } as sidebarItemProps,
  sizes: {
    key: "sizes",
    label: "Sizes",
    type: "checkbox",
    options: [
      {
        key: "30.0",
        label: "30.0",
        value: "30.0",
      },
      {
        key: "30.5",
        label: "30.5",
        value: "30.5",
      },
      {
        key: "31.0",
        label: "31.0",
        value: "31.0",
      },
      {
        key: "31.5",
        label: "31.5",
        value: "31.5",
      },
      {
        key: "32.0",
        label: "32.0",
        value: "32.0",
      },
      {
        key: "32.5",
        label: "32.5",
        value: "32.5",
      },
      {
        key: "33.0",
        label: "33.0",
        value: "33.0",
      },
    ],
  } as sidebarItemProps,
  priceRange: {
    key: "priceRange",
    label: "Price Range",
    type: "radio",
    options: [
      {
        key: "1",
        label: "Less than 1.000.000",
        value: "1",
      },
      {
        key: "2",
        label: "1.000.000 - 3.000.000",
        value: "2",
      },
      {
        key: "3",
        label: "3.000.000 - 7.000.000",
        value: "3",
      },
      {
        key: "4",
        label: "7.000.000 - 15.000.000",
        value: "4",
      },
      {
        key: "5",
        label: "More than 15.000.000",
        value: "5",
      },
    ],
  } as sidebarItemProps,
};

const productItem: ProductInterface = {
  modelId: "air_jordan_1_mid_light",
  name: "AIR JORDAN 1 MID LIGHT CARDINAL CURRY (GS) [554725-201]",
  theme: "91-7329.jpg",
  images: ["/91-7329.jpg", "/91-7329.jpg", "/91-7329.jpg"],
  price: 4200000,
  promotion: 30,
  category: "AIR JORDAN 6",
  brand: {name: "Nike", slug: "nike"},
  productSizes: ["40.0", "40.5", "41.0", "42.0", "43.0"],
  status: "available",
  description: "",
};

export const getStaticProps : GetStaticProps = async () => {
  await dbConnector()

  const products = await ProductModel.find()

  return {
    props: {
      products: JSON.parse(JSON.stringify(products))
    }
  }
} 

export default function Shop<NextPage>({products}) {
  console.log(products)
  return (
    <>
      <Head>
        <title>Sneaker Store - Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/main-logo.jpg" />
      </Head>
      <main>
        <Layout>
          <Row gutter={16}>
            <Col span={4}>
              <ShopSidebar
                brands={SidebarItems.brands}
                sizes={SidebarItems.sizes}
                priceRange={SidebarItems.priceRange}
              />
            </Col>
            <Col span={20}>
              <Row gutter={16}>
                <Col span={6}>
                  <Product {...productItem} />
                </Col>
                <Col span={6}>
                  <Product {...productItem} />
                </Col>
                <Col span={6}>
                  <Product {...productItem} />
                </Col>
                <Col span={6}>
                  <Product {...productItem} />
                </Col>
                <Col span={6}>
                  <Product {...productItem} />
                </Col>
                <Col span={6}>
                  <Product {...productItem} />
                </Col>
              </Row>
              <Row className="mt-20">
                <Col span={24} className="flex justify-center">
                  <Pagination defaultCurrent={1} total={100} />
                </Col>
              </Row>
            </Col>
          </Row>
        </Layout>
      </main>
    </>
  );
}
